parameters:
    user_csv_url: '%env(resolve:USER_CSV_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


#    Appto\User\Infrastructure\Persistence\:
#        resource: '%kernel.project_dir%/src/Appto/User/Infrastructure/Persistence/**/*Repository.php'
#        autoconfigure: true

    Appto\User\Infrastructure\Persistence\Csv\:
        resource: '%kernel.project_dir%/src/Appto/User/Infrastructure/Persistence/Csv/**/*{Assembler}.php'
        autoconfigure: true

    Appto\User\Domain\UserRepository: '@Appto\User\Infrastructure\Persistence\Csv\CsvUserRepository'
    Appto\User\Domain\Criteria\CriteriaComposite: '@Appto\User\Infrastructure\Persistence\Csv\Criteria\CsvCriteriaComposite'

    Appto\User\Infrastructure\Persistence\Csv\CsvUserRepository:
        arguments:
            - '@Feeder\FeedReader\CsvFeedReader'
            - '@Appto\User\Infrastructure\Persistence\Csv\CsvUserAssembler'

    Appto\User\Infrastructure\Persistence\Csv\Criteria\CsvCriteriaComposite:
        calls:
            - setProviders:
                   - { country: 'Appto\User\Infrastructure\Persistence\Csv\Criteria\CsvCountryCriteria', activationLength: 'Appto\User\Infrastructure\Persistence\Csv\Criteria\CsvActivationLengthCriteria', order: 'Appto\User\Infrastructure\Persistence\Csv\Criteria\CsvOrderCriteria'}

#        calls:
#            - setCriteria:
#                #arguments:
#                    - { param1: '@Appto\User\Infrastructure\Persistence\Csv\Criteria\OrderByNameAndLastNameCriteria'}
#                    - { param1: '@Appto\User\Infrastructure\Persistence\Csv\Criteria\CsvCountryCriteria', param2: '@Appto\User\Infrastructure\Persistence\Csv\Criteria\CsvActivationLengthCriteria', param3: '@Appto\User\Infrastructure\Persistence\Csv\Criteria\OrderByNameAndLastNameCriteria'}

    #            -   method: setCriteria
#                arguments:
#                    - { param1: '@Appto\User\Infrastructure\Persistence\Csv\Criteria\OrderByNameAndLastNameCriteria'}



    #Feed Reader Service
    Feeder\FeedReader\CsvFeedReader:
        arguments: ['@Feeder\Resource\HttpResource', '@Feeder\FeedReader\Separator']

    Feeder\Resource\HttpResource:
        arguments: ['%user_csv_url%']

    Feeder\FeedReader\Separator:
        arguments: ["\n", ","]


